language: java

jdk:
  - openjdk11

addons:
  ssh_known_hosts: kotlin.link

before_install:
  - nvm install 10

install:
  - yarn --cwd app-frontend install
  - ./gradlew assemble

script:
  #  - yarn --cwd app-frontend run pack
  #  - curl https://kotlin.link/api/readme > readme/README.adoc
  - ./gradlew check installDist
  - docker build -t "heapy/awesome:b${TRAVIS_BUILD_NUMBER}" -t "heapy/awesome:latest" ./app-backend/

deploy:
  - provider: script
    script: bash .ci/deploy-docker.sh
    skip_cleanup: true
    on:
      branch: master
      repo: KotlinBy/awesome-kotlin

before_cache:
  - rm -f  "${HOME}/.gradle/caches/modules-2/modules-2.lock"
  - rm -rf "${HOME}/.gradle/caches/*/plugin-resolution/"
  - rm -rf "${HOME}/.gradle/caches/*/fileHashes/"
cache:
  yarn: true
  directories:
    - "${HOME}/.gradle/caches/"
    - "${HOME}/.gradle/wrapper/"

git:
  depth: 1
